// Code generated by "stringer -type Code"; DO NOT EDIT

package errors

import "fmt"

const _Code_name = "EndOfIteratorErrorNilObservableErrorNilEventStreamErrorNilObserverErrorUndefinedError"

var _Code_index = [...]uint8{0, 18, 36, 55, 71, 85}

func (i Code) String() string {
	if i >= Code(len(_Code_index)-1) {
		return fmt.Sprintf("Code(%d)", i)
	}
	return _Code_name[_Code_index[i]:_Code_index[i+1]]
}
