// Code generated by "stringer -type ErrorCode"; DO NOT EDIT

package errors

import "fmt"

const _ErrorCode_name = "EndOfIteratorErrorNilObservableErrorNilEventStreamErrorNilObserverErrorUndefinedError"

var _ErrorCode_index = [...]uint8{0, 18, 36, 55, 71, 85}

func (i ErrorCode) String() string {
	if i >= ErrorCode(len(_ErrorCode_index)-1) {
		return fmt.Sprintf("ErrorCode(%d)", i)
	}
	return _ErrorCode_name[_ErrorCode_index[i]:_ErrorCode_index[i+1]]
}
